name: Check Requirements

on:
  pull_request:
    branches:
      - main

jobs:
  check-requirements:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: pip install pipreqs

      - name: Generate Requirements from Code
        run: pipreqs . --force --ignore .github --savepath generated_requirements.txt

      - name: Compare Requirements
        run: |
          diff -u <(sort 5.Model_Deployment/requirements.txt) <(sort generated_requirements.txt) || (echo "Mismatch in requirements!" && exit 1)
